import { useEffect, useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { alphabet, alphabetUpper, symbols, numbers } from '../lib/collections';
import styles from '../styles/Home.module.scss';

interface PasswordConfig {
  length: number;
  count: number;
  includeSymbols: boolean;
  includeNumbers: boolean;
  includeUppercase: boolean;
  includeLowerCase: boolean;
}

export function generatePassword(config: PasswordConfig): string {
  let totalCollection: string[] = [];

  if (config.includeUppercase) {
    totalCollection = totalCollection.concat(alphabetUpper.split(''));
  }
  if (config.includeLowerCase) {
    totalCollection = totalCollection.concat(alphabet.split(''));
  }
  if (config.includeNumbers) {
    totalCollection = totalCollection.concat(numbers.split(''));
  }
  if (config.includeSymbols) {
    totalCollection = totalCollection.concat(symbols.split(''));
  }

  const values = crypto.getRandomValues(new Uint8Array(config.length));

  let password = '';

  for (let i = 0; i < config.length; i++) {
    const index = values[i] % totalCollection.length;
    password += totalCollection[index];
  }

  return password;
}

export default function Home() {
  const [config, setConfig] = useState<PasswordConfig>({
    length: 16,
    count: 1,
    includeSymbols: true,
    includeNumbers: true,
    includeUppercase: true,
    includeLowerCase: true,
  });

  const [password, setPassword] = useState<string>();

  useEffect(() => {
    setPassword(generatePassword(config));
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>{password}</p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
