name: Rust

on:
  push:
    branches: ['trunk']
  pull_request:
    branches: ['trunk']

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Trunk
        run: wget -qO- https://github.com/thedodd/trunk/releases/download/v0.16.0/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: Build Site
        run: ./trunk build --release

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # Name of the artifact to deploy
          folder: dist
